"""empty message

Revision ID: 610a0a95d308
Revises: 2787030dcafc
Create Date: 2022-12-23 18:21:54.568078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610a0a95d308'
down_revision = '2787030dcafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
