"""empty message

Revision ID: 642146f0363c
Revises: c624ae511bf8
Create Date: 2022-12-30 17:57:15.281279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642146f0363c'
down_revision = 'c624ae511bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.drop_column('hour')

    # ### end Alembic commands ###
