"""empty message

Revision ID: d479dbf54468
Revises: 642146f0363c
Create Date: 2022-12-30 17:59:59.994582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd479dbf54468'
down_revision = '642146f0363c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
