"""empty message

Revision ID: ec7c35dade96
Revises: a5cf7a7cf51e
Create Date: 2022-12-28 01:38:25.686633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7c35dade96'
down_revision = 'a5cf7a7cf51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Next', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('Past', sa.Boolean(), nullable=False))

    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('interviewer', schema=None) as batch_op:
        batch_op.drop_column('Past')
        batch_op.drop_column('Next')

    # ### end Alembic commands ###
